### ISSUE TITLE
Where do you use helper.h in your test-map.cpp?

### ISSUE THREAD

**Issue by jessica-cheng** [hurda21/cs4500-a1-part2#14]
Hi, we are running into an error when we run our Makefile where you are including helper.h in your test-map.cpp but there is no helper.h in your repo.

**Comment by jessica-cheng** [comment]
If it's an optional import, then can you please remove it? Because when we run the provided Makefile from the instructors, it's giving an error bc it's expecting a helper.h file.

**Comment by jessica-cheng** [comment]
We have found the cause of the problem. The Makefile expects a helper.h file in your repo which you do not have. Please get rid of the include helper.h in test-map.cpp

**Comment by brycedewitt** [comment]
@jessica-cheng that file was something we needed for our own implementation, since the imports didn't include all the files we needed (we had some seperate files with the primitives), so that helper file was a way for us to include that in the tests.

You can make an empty `helper.h` file in your repo, then include it in the files being copied over with the make commands, that'll allow it to compile.

@hurda21 we've already taken the commit hash from earlier in your repo and submitted so feel free to make any changes they need

**Comment by jessica-cheng** [comment]
Alright, we made a blank helper.h and copied that into our Makefile and that solved the problem. Thanks!

**Comment by hurda21** [comment]
We just removed helper.h if it still works, then great! But don't think it's needed now.

**Comment by edchrepo** [comment]
Added it back, sorry for the confusion
