### ISSUE TITLE
String class

### ISSUE THREAD

**Issue by sbhornjr** [hurda21/cs4500-a1-part2#3]
Hey guys, first off the standing pull request (not made by me) would really fix a lot of issues. On top of that, according to the assignment Maps are supposed to support Strings as well as generic Objects. It would be really helpful if you could spec a String.h file (we used Thomas' spec in this piazza post: https://piazza.com/class/k51bluky59n2jr?cid=330 - it seems like the best spec) and maybe write some tests that use Strings as well. Thanks, let me know what you're thinking.

**Comment by brycedewitt** [comment]
Seconding this issue

**Comment by brycedewitt** [comment]
Well so also, it would just generally be helpful right now to know how you intend to implement your `String` class too, will it be a descendant  of `Object`? It seems the general reasoning among the class has been to have an `Object` class  with `int`, `float`, `bool`, and `String` as wrapped primitive subclasses, so this type of implementation would fit a lot nicer with our existing code personally.

An alternative way of doing this could be to have a `Map` superclass, with `int`, `float`, `bool`, and `Object/String` subclasses, which has the following benefits:

- Space efficiency (don't need to wrap primitives)
- Speed efficiency (won't need to compare or wrap objects)
- Compatibility (an `Object` Map would be able to hold wrapped objects for the primitives if that's how someone else implemented it)

I think our team would prefer the second option since that gives us the most flexibility with compatibility for the other implementations we've had to do for Queue and Array.

**Comment by dodecahedronal** [comment]
Thirding this issue - I think the pull request being merged would be extremely helpful. 

The way my team did things was to use the object.h and string.h provided by the professor for efficiency’s sake. This way, the class could handle both objects (which bool, int, and float are inherently a part of) and strings.

**Comment by sbhornjr** [comment]
How are bools, ints, and floats inherently part of the Object class that we created?

**Comment by dodecahedronal** [comment]
Sorry, I phrased that poorly. You can just derive a bool object from the object class, like how in Java there’s an Object Integer as opposed to the native int.

**Comment by hurda21** [comment]
Hey everyone, 

We didn't implement the String class because we were designing under the assumption that Strings would inherit from the Object class, similarly to the previous assignment. We will definitely be implementing a String.h class for clarity.

@brycedewitt Could you explain a little more in detail your alternative way of having the Map as a superclass? The first way was what we were originally planning, but if you believe it'll save space/be more efficient, implementing that would be beneficial.

**Comment by hurda21** [comment]
Just added object.h and string.h from the uniform specs

**Comment by sbhornjr** [comment]
What he's saying is to have a Map class, and then for example a StringMap class that inherits from it so that we can put Strings in without casting from Objects. There's a lot more about this on Piazza too.

**Comment by hurda21** [comment]
Switched the object.h and string.h to the implementation from this repo: https://github.com/chasebish/cwc_object_string

Would recommend it for you guys too. Seems like people are collectively adopting it.

**Comment by hurda21** [comment]
@steven-horn Gotcha, that makes sense.

There are a couple issues I see with that, though. Let me know what you guys think:
1) Redundancy in code - StringMap, IntMap, BoolMap, etc. will all have very similar functions, leading to repeated code. The ObjectMap would need the wrapper classes for compatibility, as @brycedewitt said, so it would be double repeated code.
2) The typed Maps would only be used in the special cases where every single key and value is the same type, which could be uncommon. I know the specs said Map generally should map Objects to Objects, Strings to Strings, etc, but it's kind of vague because "Objects to Objects" could mean a lot of things.

It does seem a little redundant in implementation, but I see the value in saving space / increasing speed. 

Thoughts?

**Comment by hurda21** [comment]
A compromise could be that our KeyValue class is the one we implement subclasses for (IntKeyValue, BoolKeyValue, StringKeyValue, etc). Then, the Map could have mixed typings without having _every_ entry be Object to Object mapping (which would require the wrapper classes).

**Comment by sbhornjr** [comment]
The assignment says that Maps only need to support String to String and Object to Object. So, you would only need an ObjectMap and a StringMap class. It seems like everything is up for interpretation, so you could easily say that you took Object to Object to mean simply Objects, not classes that inherit Objects. We just got done with our Queue implementation, and the people who wrote the spec had a Queue (for objects) and a StrQueue. Yes, there is some code duplication, but only in methods that include those types specifically (for your spec, it would be get, set, remove, getKeys, and getItems). 

The problem with your solution is that when you are receiving a String from a get(), for example, the Map class would still be returning an Object, so you would have to dynamic_cast it to a String in the test, which is exactly would professor Vitek seems to want us to avoid.

**Comment by hurda21** [comment]
True - just got done reading the thread about casting. It does seem that the prof wants us to avoid - we're gonna go with the typed Map implementation - will push shortly.

**Comment by hurda21** [comment]
@dodecahedronal Re-reading the assignment specs, it does mention only Objects and Strings need to be supported. You could argue that may include primitive types, but it actually seems redundant to implement an IntMap/FloatMap/BoolMap when looking at it practically.

**Comment by sbhornjr** [comment]
I agree with the last comment. Thanks for fixing the API! Do you plan on updating the tests to reflect the update (adding/changing tests for String* and not just Object*)?

**Comment by hurda21** [comment]
For sure! And yes we will be adding tests shortly to reflect the changes

**Comment by hurda21** [comment]
Just pushed - let me know if the test file is good for your guys' implementations / any more issues you see.

Thanks!

**Comment by brycedewitt** [comment]
@hurda21 just a quick update, line 58 of test-map.cpp, can you just add a semicolon after that `clear()`? I think that wraps up everything for my team here, thanks!

**Comment by sbhornjr** [comment]
A small thing - the length() function is void but it should return a size_t.

**Comment by sbhornjr** [comment]
Also, I believe that getKeys and getValues should return Object** and String** instead of Object* and String*

**Comment by sbhornjr** [comment]
Sorry i keep posting, but I think I found an issue with your tests of testStringMap(). If you create a new String(), the String class will presumably make its value be an empty string. So, when you set the first key-Value pair, it will be “”-“”. The second key-value pair will also be “”-“”, but since hashmaps don’t allow for duplicate keys, the first pair will be replaced, so the map length would be 1 instead of 2, but your tests assume it would be 2 there.

I think the best way to fix this would be to make the strings have any value other than empty (String* s1 = new String(“hello”); String* s2 = new String(“goodbye”); etc). 

The map class is also missing a semi colon at the end of the class.

**Comment by hurda21** [comment]
Just fixed all the things above - keep me posted about other minor bugs
